### ISSUE TITLE
Fix palette setting

### ISSUE THREAD

**Issue by loudar** [mellodoot/OpenTerminal#2]
https://github.com/mellodoot/OpenTerminal/blob/a6607a006942e4f987b790360368761d5b4b72c9/public/scripts/main.js#L302

```js
 if (palette.constructor === Array) { 
```

**Comment by mellodoot** [comment]
is there much benefit to distinguishing palettes as arrays this way? afaik `Array.isArray()` is more widely used

**Comment by loudar** [comment]
Not specifically, but personally I like checking .constructor more because you can use the same way of checking for any class and not just arrays, but that's a style thing.

**Comment by mellodoot** [comment]
should be good!
